In [3]:
import pandas as pd

import psycopg2
import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_URL = os.getenv("DATABASE_URL")

In [4]:
conn = psycopg2.connect(DATABASE_URL)
cursor = conn.cursor()
# Fetch all processed data
cursor.execute("SELECT * FROM ads_raw WHERE status = 'done'")
columns = [description[0] for description in cursor.description]
rows = cursor.fetchall()

# Convert to DataFrame
conn.close()
df = pd.DataFrame(rows, columns=columns)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5879 entries, 0 to 5878
Data columns (total 19 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hash_id           5879 non-null   str
 1   title             5879 non-null   str
 2   link              5879 non-null   str
 3   img_url           5876 non-null   str
 4   total_price_eur   0 non-null      object
 5   price_m2_eur      5851 non-null   str
 6   price_m2_bgn      5851 non-null   str
 7   size_m2           5851 non-null   str
 8   description       5879 non-null   str
 9   floor             5173 non-null   str
 10  akt16             5001 non-null   str
 11  energy_class      5241 non-null   str
 12  potreblenie       5241 non-null   str
 13  broker_commision  5818 non-null   str
 14  additional_notes  5851 non-null   str
 15  status            5879 non-null   str
 16  extras            3965 non-null   str
 17  scraped_at        5879 non-null   datetime64[us]
 18  last_updated      5879 non-null   datetime64[us]
dtypes: datetime64[us](2), object(1), str(16)
memory usage: 872.8+ KB

In [27]:
df.head()

,hash_id,title,link,price_m2_eur,price_m2_bgn,size_m2,description,floor,akt16,energy_class,potreblenie,broker_commision,additional_notes,status,scraped_at,last_updated,extras
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,3 333,6 519.43,12,"Строително-инвестиционна компания Идея Хоум, п...",,Да,NaN,NaN,Не,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:14.999578,2026-02-16 16:43:51.616580,ТЕЦ
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,78,152.78,896,УПИ с площ от 896 кв. м. в местността Купен до...,NaN,NaN,NaN,NaN,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008348,2026-02-16 17:08:29.392911,Регулация
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,2 835,5 545.72,31,"Dotwon Real Estate, част от Dotwon Group, пред...",0 от 7,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008562,2026-02-16 17:08:29.394527,
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1 888,3 692.13,49,ИМА ВЪЗМОЖНОСТ ЗА ЗАКУПУВАНЕ НА ПАРКОМЯСТО. Пр...,1 от 6,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008903,2026-02-16 17:08:29.394702,Необзаведен; Паркомясто
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1 745,3 413.81,55,След основен ремонт. Едностаен апартамент в ту...,2 от 3,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.009103,2026-02-16 17:08:29.394804,

In [28]:
df["status"].unique().tolist()

['done']

In [29]:
df["price_m2_eur"]

0       3 333
1          78
2       2 835
3       1 888
4       1 745
        ...
6216    2 680
6217    2 361
6218    2 380
6219    2 500
6220    2 611
Name: price_m2_eur, Length: 6221, dtype: str

###  Transform the columns to the appropriate format

In [30]:
df.loc[0, "price_m2_eur"].strip()

'3 333'

In [31]:
df.head()

,hash_id,title,link,price_m2_eur,price_m2_bgn,size_m2,description,floor,akt16,energy_class,potreblenie,broker_commision,additional_notes,status,scraped_at,last_updated,extras
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,3 333,6 519.43,12,"Строително-инвестиционна компания Идея Хоум, п...",,Да,NaN,NaN,Не,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:14.999578,2026-02-16 16:43:51.616580,ТЕЦ
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,78,152.78,896,УПИ с площ от 896 кв. м. в местността Купен до...,NaN,NaN,NaN,NaN,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008348,2026-02-16 17:08:29.392911,Регулация
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,2 835,5 545.72,31,"Dotwon Real Estate, част от Dotwon Group, пред...",0 от 7,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008562,2026-02-16 17:08:29.394527,
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1 888,3 692.13,49,ИМА ВЪЗМОЖНОСТ ЗА ЗАКУПУВАНЕ НА ПАРКОМЯСТО. Пр...,1 от 6,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008903,2026-02-16 17:08:29.394702,Необзаведен; Паркомясто
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1 745,3 413.81,55,След основен ремонт. Едностаен апартамент в ту...,2 от 3,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.009103,2026-02-16 17:08:29.394804,

In [32]:
cols_to_strip = ["price_m2_eur", "price_m2_bgn"]
df_copy = df.copy()
df_copy[cols_to_strip] = df_copy[cols_to_strip].apply(lambda row: row.str.replace(" ", ""))
df_copy[cols_to_strip] = df_copy[cols_to_strip].astype(float)
df_copy.info()

<class 'pandas.DataFrame'>
RangeIndex: 6221 entries, 0 to 6220
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   hash_id           6221 non-null   str
 1   title             6221 non-null   str
 2   link              6221 non-null   str
 3   price_m2_eur      6130 non-null   float64
 4   price_m2_bgn      6130 non-null   float64
 5   size_m2           6134 non-null   str
 6   description       6221 non-null   str
 7   floor             5563 non-null   str
 8   akt16             5276 non-null   str
 9   energy_class      5574 non-null   str
 10  potreblenie       5574 non-null   str
 11  broker_commision  6106 non-null   str
 12  additional_notes  6134 non-null   str
 13  status            6221 non-null   str
 14  scraped_at        6221 non-null   str
 15  last_updated      6221 non-null   str
 16  extras            2022 non-null   str
dtypes: float64(2), str(15)
memory usage: 826.4 KB

In [ ]:
# 1. convert the price & size columns to float
def convert_strip_and_convert_to_numeric(df: pd.DataFrame, cols_to_strip: list)->pd.DataFrame:
    df[cols_to_strip] = df[cols_to_strip].apply(lambda row: row.str.replace(" ", ""))
    df[cols_to_strip] = df[cols_to_strip].astype(float)
    return df

cols_to_strip = ["price_m2_eur", "price_m2_bgn"]
df_copy = df.copy()
df_copy = convert_strip_and_convert_to_numeric(df_copy, cols_to_strip)
df_copy.info()

ValueError: could not convert string to float: ''

In [34]:
import re 

match = re.search(r'\d+', str("11 ot 25"))
print(match.group())

11

In [35]:
import numpy as np

# 2. Extract the floor number from the floor column
def extract_floor_number(floor_string: str):
    if pd.isna(floor_string):
        return np.nan
    
    match = re.search(r'\d+', str(floor_string))
    return int(match.group()) if match else np.nan

df_copy["floor_clean"] = df_copy["floor"].apply(extract_floor_number)
df_copy = df_copy.drop(labels="floor", axis=1)
df_copy.head()

,hash_id,title,link,price_m2_eur,price_m2_bgn,size_m2,description,akt16,energy_class,potreblenie,broker_commision,additional_notes,status,scraped_at,last_updated,extras,floor_clean
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,3333.0,6519.43,12,"Строително-инвестиционна компания Идея Хоум, п...",Да,NaN,NaN,Не,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:14.999578,2026-02-16 16:43:51.616580,ТЕЦ,NaN
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,78.0,152.78,896,УПИ с площ от 896 кв. м. в местността Купен до...,NaN,NaN,NaN,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008348,2026-02-16 17:08:29.392911,Регулация,NaN
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,2835.0,5545.72,31,"Dotwon Real Estate, част от Dotwon Group, пред...",Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008562,2026-02-16 17:08:29.394527,,0.0
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1888.0,3692.13,49,ИМА ВЪЗМОЖНОСТ ЗА ЗАКУПУВАНЕ НА ПАРКОМЯСТО. Пр...,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008903,2026-02-16 17:08:29.394702,Необзаведен; Паркомясто,1.0
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1745.0,3413.81,55,След основен ремонт. Едностаен апартамент в ту...,Да,N/A,N/A,Да,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.009103,2026-02-16 17:08:29.394804,,2.0

In [36]:
df["broker_commision"].unique().tolist()

['Не', 'Да', nan]

In [37]:
# 3. convert the yes/no columns to bool
def convert_to_bool(value: str):
    if pd.isna(value):
        return np.nan
    
    elif value.upper() == "ДА":
        return True

    else:
        return False

bool_cols = ["akt16", "broker_commision"]
for col in bool_cols:
    df_copy[f"{col}_processed"] = df_copy[f"{col}"].apply(convert_to_bool)
    df_copy.drop(labels=col, axis=1, inplace=True)

df_copy.head()

,hash_id,title,link,price_m2_eur,price_m2_bgn,size_m2,description,energy_class,potreblenie,additional_notes,status,scraped_at,last_updated,extras,floor_clean,akt16_processed,broker_commision_processed
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,3333.0,6519.43,12,"Строително-инвестиционна компания Идея Хоум, п...",NaN,NaN,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:14.999578,2026-02-16 16:43:51.616580,ТЕЦ,NaN,True,False
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,78.0,152.78,896,УПИ с площ от 896 кв. м. в местността Купен до...,NaN,NaN,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008348,2026-02-16 17:08:29.392911,Регулация,NaN,NaN,True
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,2835.0,5545.72,31,"Dotwon Real Estate, част от Dotwon Group, пред...",N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008562,2026-02-16 17:08:29.394527,,0.0,True,True
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1888.0,3692.13,49,ИМА ВЪЗМОЖНОСТ ЗА ЗАКУПУВАНЕ НА ПАРКОМЯСТО. Пр...,N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008903,2026-02-16 17:08:29.394702,Необзаведен; Паркомясто,1.0,True,True
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1745.0,3413.81,55,След основен ремонт. Едностаен апартамент в ту...,N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.009103,2026-02-16 17:08:29.394804,,2.0,True,True

In [38]:
df_copy.loc[3, "link"]

'https://www.imoti.net/bg/obiava/prodava/sofia/ovcha-kupel/ednostaen/6176507/?sid=icNBCK&page=1'

In [39]:
# 4. Extract the neighbourhood from the title
df_copy['neighbourhood'] = df_copy['title'].str.extract(r'в София, \s*(.*)', expand=False)
df_copy.head()

,hash_id,title,link,price_m2_eur,price_m2_bgn,size_m2,description,energy_class,potreblenie,additional_notes,status,scraped_at,last_updated,extras,floor_clean,akt16_processed,broker_commision_processed,neighbourhood
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,3333.0,6519.43,12,"Строително-инвестиционна компания Идея Хоум, п...",NaN,NaN,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:14.999578,2026-02-16 16:43:51.616580,ТЕЦ,NaN,True,False,Оборище
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,78.0,152.78,896,УПИ с площ от 896 кв. м. в местността Купен до...,NaN,NaN,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008348,2026-02-16 17:08:29.392911,Регулация,NaN,NaN,True,Банкя (гр.)
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,2835.0,5545.72,31,"Dotwon Real Estate, част от Dotwon Group, пред...",N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008562,2026-02-16 17:08:29.394527,,0.0,True,True,Гео Милев
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1888.0,3692.13,49,ИМА ВЪЗМОЖНОСТ ЗА ЗАКУПУВАНЕ НА ПАРКОМЯСТО. Пр...,N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008903,2026-02-16 17:08:29.394702,Необзаведен; Паркомясто,1.0,True,True,Овча Купел
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1745.0,3413.81,55,След основен ремонт. Едностаен апартамент в ту...,N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.009103,2026-02-16 17:08:29.394804,,2.0,True,True,Фондови Жилища

In [40]:
from collections import Counter

# Collect all extras by splitting strings
all_items = []
for extras_str in df_copy['extras'].dropna():
    items = [x.strip() for x in extras_str.split(';')]
    all_items.extend(items)

# Count frequency
extra_counts = Counter(all_items)

# See most common extras
print(f"Total unique extras: {len(extra_counts)}\n")
for extra, count in extra_counts.most_common(30):
    print(f"{extra}: {count} ({count/len(df_copy)*100:.1f}%)")

Total unique extras: 53

EMPTY: 949 (15.3%)
Асансьор: 563 (9.0%)
Ново строителство: 389 (6.3%)
Необзаведен: 348 (5.6%)
ТЕЦ: 224 (3.6%)
Паркомясто: 198 (3.2%)
Ток: 190 (3.1%)
Водопровод: 182 (2.9%)
Обзаведен: 161 (2.6%)
Гараж: 126 (2.0%)
Канализация: 119 (1.9%)
Локал. отопление: 102 (1.6%)
Лукс: 102 (1.6%)
До метростанция - до 10 мин.пеш: 90 (1.4%)
WC: 86 (1.4%)
Климатик: 64 (1.0%)
Регулация: 60 (1.0%)
За жилищно строителство: 54 (0.9%)
Двор: 48 (0.8%)
Равен: 39 (0.6%)
Интернет връзка: 29 (0.5%)
Телефон: 23 (0.4%)
Подходящо за живеене: 22 (0.4%)
Подземен: 20 (0.3%)
Надземен: 11 (0.2%)
Офис сграда: 10 (0.2%)
Охрана: 10 (0.2%)
ВИЗА: 9 (0.1%)
: 8 (0.1%)
Разрешено за дом. любимец: 8 (0.1%)

In [46]:
# 6. Extract if its a garage or living building or area for building (parcel)
# "Гараж, паркомясто"; "Парцел"

# we use a vectorized approach since it's fastest
df_copy["type_of_estate"] = np.select(
    [
        df_copy["title"].str.contains("Гараж", na=False),
        df_copy["title"].str.contains("Парцел", na=False),
        df_copy["title"].str.contains("Магазин", na=False),
    ],
    ["гараж", "парцел", "магазин"],
    default="жилище"
)

df_copy["type_of_estate"].value_counts()

type_of_estate
жилище     5578
парцел      438
магазин     132
гараж        73
Name: count, dtype: int64

In [47]:
df_copy

,hash_id,title,link,price_m2_eur,price_m2_bgn,size_m2,description,energy_class,potreblenie,additional_notes,status,scraped_at,last_updated,extras,floor_clean,akt16_processed,broker_commision_processed,neighbourhood,type_of_estate
0,f86956dd334888697e09f28acb103cf8c9dfa00f0bc5d6...,"Имот - продава Гараж, паркомясто, в София, Обо...",https://www.imoti.net/bg/obiava/prodava/sofia/...,3333.0,6519.43,12,"Строително-инвестиционна компания Идея Хоум, п...",NaN,NaN,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:14.999578,2026-02-16 16:43:51.616580,ТЕЦ,NaN,True,False,Оборище,гараж
1,54f96cec5e494e296451bd6588e2153de45b96bc8846ab...,"Имот - продава Парцел, в София, Банкя (гр.)",https://www.imoti.net/bg/obiava/prodava/sofia/...,78.0,152.78,896,УПИ с площ от 896 кв. м. в местността Купен до...,NaN,NaN,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008348,2026-02-16 17:08:29.392911,Регулация,NaN,NaN,True,Банкя (гр.),парцел
2,db86942d1b1b8fc970e32022d5f548165d9813d4212ad3...,"Имот - продава Магазин, в София, Гео Милев",https://www.imoti.net/bg/obiava/prodava/sofia/...,2835.0,5545.72,31,"Dotwon Real Estate, част от Dotwon Group, пред...",N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008562,2026-02-16 17:08:29.394527,,0.0,True,True,Гео Милев,магазин
3,ca420156d8e9fbfbd273afed51b5b294de1496404facea...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1888.0,3692.13,49,ИМА ВЪЗМОЖНОСТ ЗА ЗАКУПУВАНЕ НА ПАРКОМЯСТО. Пр...,N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.008903,2026-02-16 17:08:29.394702,Необзаведен; Паркомясто,1.0,True,True,Овча Купел,жилище
4,528685330d09ed04f6d4182b1b75bff4340766ce5aac35...,"Имот - продава Едностаен апартамент, в София, ...",https://www.imoti.net/bg/obiava/prodava/sofia/...,1745.0,3413.81,55,След основен ремонт. Едностаен апартамент в ту...,N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 16:58:15.009103,2026-02-16 17:08:29.394804,,2.0,True,True,Фондови Жилища,жилище
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6216,e7c20c29939aa363004c2b270277574739bf5775761580...,"Имот - продава Тристаен апартамент, в София, М...",https://www.imoti.net/bg/obiava/prodava/sofia/...,2680.0,5241.01,111,"""Бориса Апартментс 2"" е затворен комплекс с мо...",N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 17:22:39.663301,2026-02-17 19:16:57.848757,NaN,1.0,True,True,Манастирски ливади Изток,жилище
6217,5e859d392492ad71fb2ecdb32733badcc69b2bb2a84745...,"Имот - продава Тристаен апартамент, в София, Д...",https://www.imoti.net/bg/obiava/prodava/sofia/...,2361.0,4617.62,126,New Estates има удоволствието да представя про...,N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 17:22:39.663608,2026-02-17 19:16:57.848779,NaN,3.0,True,True,Дружба 2,жилище
6218,766bd265e225f4db1bfeda0ba5f8b43fdea9782d92a21c...,"Имот - продава Тристаен апартамент, в София, Д...",https://www.imoti.net/bg/obiava/prodava--v-str...,2380.0,4654.56,125,ЕРА Младост предлага БЕЗ КОМИСОННА! Двустайни ...,N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 17:22:39.663886,2026-02-17 19:16:57.848804,NaN,3.0,NaN,True,Дружба 2,жилище
6219,d92ab7126b07222b7e5189b66cb79e91d7cad2812a0f8a...,"Имот - продава Тристаен апартамент, в София, П...",https://www.imoti.net/bg/obiava/prodava/sofia/...,2500.0,4889.58,119,ВИЖТЕ ВИДЕО ОТ ЗАСНЕМАНЕ С ДРОН: https://bit.l...,N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 17:22:39.664157,2026-02-17 19:16:57.848839,NaN,2.0,True,True,Панчарево (с.),жилище
6220,840664968bd39943642cda13e547101a157e36a5d5c9b7...,"Имот - продава Тристаен апартамент, в София, Х...",https://www.imoti.net/bg/obiava/prodava/sofia/...,2611.0,5107.46,114,ЕРА Младост продава апартамент в сграда с разр...,N/A,N/A,Посочената цена не включва местни данъци и такси.,done,2026-02-15 17:22:39.664410,2026-02-17 19:16:57.848871,NaN,5.0,True,True,Хладилника,жилище